# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xabi93
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: no
